<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LTIN487042" failures="1" tests="3" name="Test" time="0.066" errors="0" timestamp="2024-03-20T10:33:06 IST">
  <testcase classname="practiceTestNG.Listener1" name="fun1" time="0.009"/>
  <testcase classname="practiceTestNG.Listener1" name="fun2" time="0.007">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
at practiceTestNG.Listener1.fun2(Listener1.java:16)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- fun2 -->
  <testcase classname="practiceTestNG.Listener1" name="fun3" time="0.0">
    <skipped/>
  </testcase> <!-- fun3 -->
</testsuite> <!-- Test -->
